
module Babel
  VERSION = '0.1.4'

  CHUNKS = [
'ACM',
'ANSI',
'ASAP',
'Ada',
'Ames',
'Arab',
'Argo',
'Asia',
'Ave',
'BSD',
'Bach',
'CDC',
'CEO',
'CMOS',
'CPU',
'CPUs',
'Cray',
'DOS',
'Dan',
'EDP',
'EGA',
'FIFO',
'GPSS',
'Greg',
'Hz',
'IBM',
'IEEE',
'Inc',
'Iran',
'Jill',
'Jr',
'July',
'June',
'LEDs',
'Liz',
'Lyle',
'MHz',
'MIT',
'Mary',
'Matt',
'Mr',
'Mrs',
'Ms',
'NFS',
'Nazi',
'NeWS',
'OEM',
'OEMS',
'OK',
'OS',
'Ohio',
'PC',
'PCs',
'PDP',
'PhD',
'QA',
'RCS',
'ROM',
'RSX',
'Rick',
'Roy',
'SCCS',
'SMTP',
'Salz',
'Sam',
'Sr',
'TCP',
'TeX',
'UART',
'UCLA',
'USC',
'USG',
'Unix',
'Utah',
'VAR',
'VCR',
'VMS',
'Vax',
'York',
'Zulu',
'abbe',
'abed',
'abet',
'able',
'ably',
'abut',
'ace',
'aced',
'acer',
'aces',
'ache',
'acid',
'acme',
'acne',
'acre',
'act',
'acts',
'ad',
'add',
'adds',
'ado',
'ads',
'afar',
'aft',
'agar',
'age',
'aged',
'ager',
'ages',
'ago',
'agog',
'ague',
'ah',
'aid',
'aide',
'aids',
'ail',
'ails',
'aim',
'aims',
'air',
'airs',
'airy',
'ajar',
'akin',
'alas',
'alba',
'ale',
'alee',
'alga',
'all',
'ally',
'alma',
'alms',
'aloe',
'alps',
'also',
'alto',
'alum',
'am',
'amen',
'amid',
'ammo',
'amok',
'amp',
'amps',
'ams',
'amyl',
'an',
'anal',
'and',
'ands',
'anew',
'anon',
'ant',
'ante',
'anti',
'ants',
'anus',
'any',
'ape',
'aped',
'aper',
'apes',
'apex',
'apse',
'apt',
'aqua',
'arc',
'arch',
'arcs',
'are',
'area',
'ares',
'arid',
'ark',
'arm',
'arms',
'army',
'art',
'arts',
'as',
'ash',
'ask',
'asks',
'asp',
'ass',
'at',
'ate',
'atom',
'atop',
'aunt',
'aura',
'auto',
'aver',
'avid',
'avow',
'away',
'awe',
'awed',
'awl',
'awls',
'awry',
'ax',
'axe',
'axed',
'axer',
'axes',
'axis',
'axle',
'axon',
'aye',
'ayer',
'ayes',
'babe',
'baby',
'back',
'bad',
'bade',
'bads',
'bag',
'bags',
'bah',
'bail',
'bait',
'bake',
'bald',
'bale',
'balk',
'ball',
'balm',
'ban',
'band',
'bane',
'bang',
'bank',
'bans',
'bar',
'barb',
'bard',
'bare',
'bark',
'barn',
'bars',
'bas',
'base',
'bash',
'bask',
'bass',
'bat',
'bath',
'bats',
'baud',
'bawl',
'bay',
'bays',
'be',
'bead',
'beak',
'beam',
'bean',
'bear',
'beat',
'beau',
'beck',
'bed',
'beds',
'bee',
'beef',
'been',
'beep',
'beer',
'bees',
'beet',
'beg',
'begs',
'bell',
'belt',
'bely',
'bend',
'bent',
'bes',
'best',
'bet',
'beta',
'beth',
'bets',
'bevy',
'bias',
'bib',
'bibs',
'bid',
'bide',
'bids',
'bier',
'big',
'bike',
'bile',
'bilk',
'bill',
'bin',
'bind',
'bing',
'bins',
'bird',
'bit',
'bite',
'bits',
'blab',
'bled',
'blew',
'blip',
'blob',
'bloc',
'blot',
'blow',
'blue',
'blur',
'boar',
'boat',
'bob',
'bobs',
'bode',
'body',
'bog',
'bogs',
'boil',
'bold',
'boll',
'bolt',
'bomb',
'bond',
'bone',
'bong',
'bony',
'boo',
'boob',
'book',
'boom',
'boon',
'boor',
'boos',
'boot',
'bore',
'born',
'boss',
'both',
'bout',
'bow',
'bowl',
'bows',
'box',
'boy',
'boys',
'bra',
'brae',
'brag',
'bran',
'bras',
'brat',
'bray',
'bred',
'brew',
'brig',
'brim',
'brow',
'buck',
'bud',
'buds',
'buff',
'bug',
'bugs',
'bulb',
'bulk',
'bull',
'bum',
'bump',
'bums',
'bun',
'bunk',
'buns',
'bunt',
'buoy',
'burl',
'burn',
'burp',
'burr',
'bury',
'bus',
'bush',
'buss',
'bust',
'busy',
'but',
'butt',
'buy',
'buys',
'buzz',
'by',
'bye',
'byes',
'byte',
'cab',
'cabs',
'cad',
'cafe',
'cage',
'cake',
'calf',
'call',
'calm',
'came',
'camp',
'can',
'cane',
'cans',
'cap',
'cape',
'caps',
'car',
'card',
'care',
'cars',
'cart',
'case',
'cash',
'cask',
'cast',
'cat',
'cats',
'cave',
'caw',
'caws',
'cell',
'cent',
'chap',
'char',
'chat',
'chef',
'chew',
'chin',
'chip',
'chop',
'chum',
'cite',
'city',
'clad',
'clam',
'clan',
'clap',
'claw',
'clay',
'clip',
'clod',
'clog',
'club',
'clue',
'coal',
'coat',
'coax',
'cock',
'cod',
'code',
'cods',
'coil',
'coin',
'coke',
'cold',
'colt',
'comb',
'come',
'cone',
'cons',
'coo',
'cook',
'cool',
'coon',
'coop',
'cop',
'cope',
'cops',
'copy',
'cord',
'core',
'cork',
'corn',
'cost',
'cot',
'cots',
'cove',
'cow',
'cowl',
'cows',
'cozy',
'crab',
'crag',
'cram',
'crap',
'crew',
'crib',
'crop',
'crow',
'crux',
'cry',
'cub',
'cube',
'cubs',
'cue',
'cued',
'cues',
'cuff',
'cull',
'cult',
'cup',
'cups',
'cur',
'curb',
'cure',
'curl',
'curs',
'curt',
'cusp',
'cuss',
'cut',
'cute',
'cuts',
'cyst',
'czar',
'dad',
'dads',
'dale',
'dam',
'dame',
'damn',
'damp',
'dams',
'dare',
'dark',
'darn',
'dart',
'dash',
'data',
'date',
'dawn',
'day',
'days',
'daze',
'dead',
'deaf',
'deal',
'dean',
'dear',
'debt',
'deck',
'deed',
'deem',
'deep',
'deer',
'defy',
'dell',
'demo',
'den',
'dens',
'dent',
'deny',
'desk',
'dew',
'dews',
'dewy',
'dial',
'dice',
'did',
'die',
'died',
'dies',
'diet',
'dig',
'digs',
'dike',
'dim',
'dime',
'dims',
'din',
'dine',
'dint',
'dip',
'dips',
'dire',
'dirt',
'disc',
'dish',
'disk',
'dive',
'do',
'dock',
'doer',
'does',
'dog',
'dogs',
'dole',
'doll',
'dome',
'don',
'done',
'dons',
'doom',
'door',
'dope',
'dose',
'dot',
'dote',
'doth',
'dots',
'dove',
'down',
'doze',
'drab',
'drag',
'draw',
'drew',
'drip',
'drop',
'drug',
'drum',
'dry',
'dual',
'dub',
'dubs',
'duck',
'dude',
'due',
'duel',
'dues',
'dug',
'duke',
'dull',
'duly',
'dumb',
'dump',
'dune',
'dusk',
'dust',
'duty',
'dye',
'dyed',
'dyer',
'dyes',
'each',
'ear',
'earl',
'earn',
'ears',
'ease',
'east',
'easy',
'eat',
'eats',
'ebb',
'ebbs',
'echo',
'eddy',
'edge',
'edit',
'eel',
'eels',
'egg',
'eggs',
'ego',
'egos',
'eke',
'eked',
'ekes',
'el',
'elf',
'elk',
'elks',
'elm',
'elms',
'els',
'else',
'emit',
'end',
'ends',
'envy',
'epic',
'era',
'eras',
'ere',
'ergo',
'err',
'errs',
'espy',
'etc',
'eve',
'even',
'ever',
'eves',
'evil',
'ewe',
'ewer',
'ewes',
'exam',
'exit',
'eye',
'eyed',
'eyer',
'eyes',
'face',
'fact',
'fade',
'fag',
'fags',
'fail',
'fain',
'fair',
'fake',
'fall',
'fame',
'fan',
'fang',
'fans',
'far',
'fare',
'farm',
'fast',
'fat',
'fate',
'fats',
'fawn',
'fear',
'feat',
'fed',
'feds',
'fee',
'feed',
'feel',
'fees',
'feet',
'fell',
'felt',
'fen',
'fern',
'feud',
'few',
'fews',
'fife',
'fig',
'figs',
'file',
'fill',
'film',
'fin',
'find',
'fine',
'fins',
'fir',
'fire',
'firm',
'fish',
'fist',
'fit',
'fits',
'five',
'fix',
'flab',
'flag',
'flap',
'flat',
'flaw',
'flax',
'flea',
'fled',
'flee',
'flew',
'flip',
'flit',
'flop',
'flow',
'fly',
'foam',
'foci',
'foe',
'foes',
'fog',
'fogs',
'foil',
'fold',
'folk',
'fond',
'font',
'food',
'fool',
'foot',
'for',
'ford',
'fore',
'fork',
'form',
'fort',
'foul',
'four',
'fowl',
'fox',
'fray',
'free',
'fret',
'frog',
'from',
'fry',
'fuel',
'full',
'fume',
'fun',
'fund',
'fur',
'furs',
'fury',
'fuse',
'fuss',
'gad',
'gag',
'gags',
'gain',
'gait',
'gale',
'gall',
'game',
'gang',
'gap',
'gape',
'gaps',
'garb',
'gas',
'gash',
'gasp',
'gate',
'gave',
'gay',
'gaze',
'gear',
'gel',
'gels',
'gem',
'gems',
'gene',
'germ',
'get',
'gets',
'gift',
'gig',
'gigs',
'gild',
'gill',
'gilt',
'gin',
'gins',
'gird',
'girl',
'girt',
'give',
'glad',
'glee',
'glen',
'glow',
'glue',
'gnat',
'gnaw',
'go',
'goad',
'goal',
'goat',
'god',
'gods',
'goer',
'goes',
'gold',
'golf',
'gone',
'gong',
'good',
'gore',
'gosh',
'got',
'goth',
'goto',
'gown',
'grab',
'gray',
'grew',
'grey',
'grid',
'grim',
'grin',
'grip',
'grit',
'grow',
'grub',
'gulf',
'gull',
'gulp',
'gum',
'gums',
'gun',
'guns',
'guru',
'gush',
'gust',
'gut',
'guts',
'guy',
'guys',
'gym',
'gyms',
'ha',
'hack',
'had',
'hag',
'hail',
'hair',
'hale',
'half',
'hall',
'halt',
'ham',
'hams',
'hand',
'hang',
'hap',
'hard',
'hare',
'hark',
'harm',
'harp',
'hart',
'has',
'hash',
'hat',
'hate',
'hath',
'hats',
'haul',
'have',
'hawk',
'hay',
'hays',
'haze',
'hazy',
'he',
'head',
'heal',
'heap',
'hear',
'heat',
'heed',
'heel',
'heir',
'held',
'hell',
'helm',
'help',
'hem',
'hemp',
'hems',
'hen',
'hens',
'her',
'herb',
'herd',
'here',
'hero',
'hers',
'hew',
'hews',
'hex',
'hey',
'hid',
'hide',
'high',
'hike',
'hill',
'hilt',
'him',
'hims',
'hind',
'hint',
'hip',
'hips',
'hire',
'his',
'hiss',
'hit',
'hits',
'hive',
'hoar',
'hoax',
'hoe',
'hoer',
'hoes',
'hog',
'hogs',
'hold',
'hole',
'holy',
'home',
'hone',
'hood',
'hoof',
'hook',
'hoop',
'hoot',
'hop',
'hope',
'hops',
'horn',
'hose',
'host',
'hot',
'hour',
'how',
'howl',
'hows',
'hrs',
'hub',
'hubs',
'hue',
'hued',
'hues',
'hug',
'huge',
'hugs',
'huh',
'hull',
'hum',
'hump',
'hums',
'hung',
'hunk',
'hunt',
'hurl',
'hurt',
'hush',
'husk',
'hut',
'huts',
'hymn',
'hype',
'ice',
'iced',
'ices',
'icon',
'icy',
'id',
'idea',
'idle',
'idly',
'idol',
'if',
'ii',
'iii',
'ill',
'ills',
'illy',
'imp',
'imps',
'in',
'inch',
'ink',
'inks',
'inly',
'inn',
'inns',
'ins',
'into',
'ion',
'ions',
'ire',
'ires',
'iris',
'irk',
'irks',
'iron',
'is',
'isle',
'it',
'itch',
'item',
'its',
'iv',
'ivy',
'ix',
'jab',
'jabs',
'jack',
'jade',
'jail',
'jam',
'jams',
'jar',
'jars',
'jaw',
'jaws',
'jay',
'jazz',
'jean',
'jeep',
'jeer',
'jerk',
'jest',
'jet',
'jets',
'jig',
'jigs',
'job',
'jobs',
'jog',
'jogs',
'john',
'join',
'joke',
'jolt',
'jot',
'jots',
'joy',
'joys',
'jug',
'jugs',
'jump',
'junk',
'jury',
'just',
'jut',
'kHz',
'keel',
'keen',
'keep',
'ken',
'kept',
'key',
'keys',
'kick',
'kid',
'kids',
'kill',
'kin',
'kind',
'king',
'kiss',
'kit',
'kite',
'kits',
'knee',
'knew',
'knit',
'knob',
'knot',
'know',
'lab',
'labs',
'lace',
'lack',
'lad',
'lads',
'lady',
'lag',
'lags',
'laid',
'lain',
'lair',
'lake',
'lamb',
'lame',
'lamp',
'land',
'lane',
'lap',
'laps',
'lard',
'lark',
'lash',
'lass',
'last',
'late',
'lath',
'lava',
'law',
'lawn',
'laws',
'lay',
'lays',
'lazy',
'lead',
'leaf',
'leak',
'lean',
'leap',
'led',
'lee',
'leer',
'lees',
'left',
'leg',
'legs',
'lend',
'lens',
'lent',
'less',
'lest',
'let',
'lets',
'levy',
'lewd',
'liar',
'lick',
'lid',
'lids',
'lie',
'lied',
'lien',
'lier',
'lies',
'lieu',
'life',
'lift',
'like',
'lily',
'limb',
'lime',
'limp',
'line',
'link',
'lint',
'lion',
'lip',
'lips',
'lisp',
'list',
'lit',
'live',
'load',
'loaf',
'loan',
'lobe',
'loci',
'lock',
'loft',
'log',
'logs',
'loin',
'lone',
'long',
'look',
'loom',
'loon',
'loop',
'loot',
'lord',
'lore',
'lose',
'loss',
'lost',
'lot',
'lots',
'loud',
'love',
'low',
'lows',
'luck',
'lull',
'lump',
'lung',
'lure',
'lurk',
'lust',
'lute',
'lynx',
'lyre',
'mace',
'mad',
'made',
'maid',
'mail',
'maim',
'main',
'make',
'male',
'mall',
'malt',
'mama',
'man',
'mane',
'mans',
'many',
'map',
'maps',
'mar',
'mare',
'mark',
'mars',
'mart',
'mash',
'mask',
'mass',
'mast',
'mat',
'mate',
'math',
'mats',
'max',
'may',
'mays',
'maze',
'me',
'mead',
'meal',
'mean',
'meat',
'med',
'meek',
'meet',
'meld',
'melt',
'memo',
'men',
'mend',
'mens',
'menu',
'mer',
'mere',
'mesh',
'mess',
'met',
'meta',
'mete',
'mets',
'mew',
'mews',
'mica',
'mice',
'mid',
'mien',
'mies',
'miff',
'mild',
'mile',
'milk',
'mill',
'mind',
'mine',
'ming',
'mink',
'mint',
'mire',
'miss',
'mist',
'mite',
'mix',
'ml',
'moan',
'moat',
'mob',
'mobs',
'mock',
'mode',
'mold',
'mole',
'mom',
'moms',
'monk',
'mono',
'mood',
'moon',
'moor',
'moot',
'mop',
'mops',
'more',
'morn',
'moss',
'most',
'moth',
'move',
'mow',
'mows',
'much',
'muck',
'mud',
'muds',
'muff',
'mug',
'mugs',
'mule',
'muse',
'musk',
'must',
'mute',
'my',
'myth',
'nag',
'nags',
'nail',
'name',
'nap',
'naps',
'navy',
'nay',
'near',
'neat',
'neck',
'need',
'nest',
'net',
'nets',
'new',
'news',
'newt',
'next',
'nice',
'nick',
'nigh',
'nil',
'nine',
'nip',
'nips',
'nix',
'no',
'nod',
'node',
'nods',
'non',
'none',
'nook',
'noon',
'nope',
'nor',
'norm',
'nose',
'not',
'note',
'noun',
'now',
'nows',
'null',
'numb',
'nun',
'nuns',
'nut',
'nuts',
'oak',
'oaks',
'oar',
'oars',
'oat',
'oath',
'oats',
'obey',
'odd',
'odds',
'ode',
'oded',
'oder',
'odes',
'of',
'off',
'offs',
'oft',
'oh',
'oil',
'oils',
'oily',
'okay',
'old',
'omen',
'omit',
'on',
'once',
'one',
'oner',
'ones',
'only',
'ons',
'onto',
'oops',
'ooze',
'opal',
'open',
'opt',
'opts',
'or',
'oral',
'orb',
'ore',
'ores',
'orgy',
'orly',
'our',
'ours',
'out',
'outs',
'oval',
'oven',
'over',
'ovum',
'owe',
'owed',
'owes',
'owl',
'owls',
'own',
'owns',
'ox',
'oxen',
'pa',
'pace',
'pack',
'pact',
'pad',
'pads',
'page',
'paid',
'pail',
'pain',
'pair',
'pal',
'pale',
'pall',
'palm',
'pals',
'pan',
'pane',
'pang',
'pans',
'pant',
'papa',
'par',
'pare',
'park',
'pars',
'part',
'pas',
'pass',
'past',
'pat',
'path',
'pats',
'pave',
'paw',
'pawn',
'paws',
'pay',
'pays',
'pea',
'peak',
'peal',
'pear',
'peas',
'peat',
'peck',
'peek',
'peel',
'peep',
'peer',
'peg',
'pegs',
'pelt',
'pen',
'pend',
'pens',
'pent',
'pep',
'per',
'pest',
'pet',
'pets',
'pew',
'pews',
'pi',
'pick',
'pie',
'pied',
'pier',
'pies',
'pig',
'pigs',
'pike',
'pile',
'pill',
'pin',
'pine',
'ping',
'pink',
'pins',
'pint',
'pipe',
'piss',
'pit',
'pith',
'pits',
'pity',
'plan',
'play',
'plea',
'plod',
'plot',
'ploy',
'plug',
'plum',
'plus',
'ply',
'pod',
'pods',
'poem',
'poet',
'poke',
'pole',
'poll',
'polo',
'pomp',
'pond',
'pony',
'poof',
'pool',
'poor',
'pop',
'pope',
'pops',
'pore',
'pork',
'porn',
'port',
'pose',
'post',
'pot',
'pots',
'pour',
'pout',
'pox',
'pray',
'prey',
'pro',
'prop',
'pros',
'prow',
'pry',
'pub',
'pubs',
'puff',
'pull',
'pulp',
'pump',
'pun',
'puns',
'punt',
'puny',
'pup',
'pupa',
'pups',
'pure',
'purr',
'push',
'puss',
'put',
'puts',
'quay',
'quit',
'quiz',
'quo',
'race',
'rack',
'raft',
'rag',
'rage',
'rags',
'raid',
'rail',
'rain',
'rake',
'ram',
'ramp',
'rams',
'ran',
'rang',
'rank',
'rant',
'rap',
'rape',
'raps',
'rapt',
'rare',
'rash',
'rasp',
'rat',
'rate',
'rats',
'rave',
'raw',
'raws',
'ray',
'rays',
're',
'read',
'real',
'ream',
'reap',
'rear',
'red',
'reds',
'reed',
'reef',
'reel',
'rein',
'rely',
'rend',
'reno',
'rent',
'res',
'rest',
'rib',
'ribs',
'rice',
'rich',
'rid',
'ride',
'rids',
'rift',
'rig',
'rigs',
'rill',
'rim',
'rime',
'rims',
'rind',
'ring',
'riot',
'rip',
'ripe',
'rips',
'rise',
'risk',
'rite',
'rive',
'road',
'roam',
'roar',
'rob',
'robe',
'robs',
'rock',
'rod',
'rode',
'rods',
'roe',
'roes',
'role',
'roll',
'romp',
'roof',
'rook',
'room',
'root',
'rope',
'rose',
'rosy',
'rot',
'rots',
'rout',
'rove',
'row',
'rows',
'rub',
'rubs',
'ruby',
'rude',
'rue',
'rues',
'rug',
'rugs',
'ruin',
'rule',
'rum',
'rump',
'run',
'rung',
'runs',
'rush',
'rust',
'rut',
'ruts',
'rye',
'sack',
'sad',
'safe',
'sag',
'sage',
'sags',
'said',
'sail',
'sake',
'sale',
'salt',
'same',
'sand',
'sane',
'sang',
'sank',
'sap',
'saps',
'sash',
'sat',
'sate',
'save',
'saw',
'saws',
'say',
'says',
'scam',
'scan',
'scar',
'scow',
'scum',
'sea',
'seal',
'seam',
'sear',
'seas',
'seat',
'sect',
'see',
'seed',
'seek',
'seem',
'seen',
'seep',
'seer',
'sees',
'self',
'sell',
'send',
'sent',
'serf',
'set',
'sets',
'sew',
'sews',
'sex',
'sham',
'she',
'shed',
'shin',
'ship',
'shit',
'shod',
'shoe',
'shop',
'shot',
'show',
'shun',
'shut',
'shy',
'sick',
'side',
'sift',
'sigh',
'sign',
'silk',
'sill',
'silt',
'sin',
'sine',
'sing',
'sink',
'sins',
'sip',
'sips',
'sir',
'sire',
'sirs',
'sit',
'site',
'sits',
'six',
'size',
'skew',
'ski',
'skim',
'skin',
'skip',
'skis',
'sky',
'slab',
'slam',
'slap',
'slat',
'slay',
'sled',
'slew',
'slid',
'slim',
'slip',
'slit',
'slop',
'slot',
'slow',
'slug',
'slum',
'slur',
'sly',
'smog',
'smug',
'snap',
'snow',
'snug',
'so',
'soak',
'soap',
'soar',
'sob',
'sobs',
'sock',
'sod',
'soda',
'sods',
'sofa',
'soft',
'soil',
'sold',
'sole',
'solo',
'some',
'son',
'song',
'sons',
'soon',
'soot',
'sore',
'sort',
'sos',
'soul',
'soup',
'sour',
'span',
'spat',
'sped',
'spin',
'spit',
'spot',
'spun',
'spur',
'spy',
'stab',
'stag',
'star',
'stay',
'stem',
'step',
'stew',
'stir',
'stop',
'stow',
'stub',
'stud',
'stun',
'sub',
'subs',
'such',
'suck',
'suds',
'sue',
'sued',
'suer',
'sues',
'suit',
'sulk',
'sum',
'sums',
'sun',
'sung',
'sunk',
'suns',
'sup',
'sure',
'surf',
'swam',
'swan',
'swap',
'sway',
'swim',
'swum',
'tab',
'tabs',
'tack',
'tact',
'tag',
'tags',
'tail',
'take',
'tale',
'talk',
'tall',
'tame',
'tan',
'tang',
'tank',
'tans',
'tap',
'tape',
'taps',
'tar',
'tars',
'tart',
'task',
'tau',
'taut',
'tax',
'taxi',
'tea',
'team',
'tear',
'teas',
'teem',
'teen',
'tell',
'ten',
'tend',
'tens',
'tent',
'term',
'test',
'text',
'than',
'that',
'thaw',
'the',
'them',
'then',
'they',
'thin',
'this',
'thud',
'thug',
'thus',
'tick',
'tide',
'tidy',
'tie',
'tied',
'tier',
'ties',
'tile',
'till',
'tilt',
'time',
'tin',
'tins',
'tint',
'tiny',
'tip',
'tips',
'tire',
'tit',
'tits',
'to',
'toad',
'toe',
'toed',
'toes',
'toil',
'told',
'toll',
'tom',
'tomb',
'toms',
'ton',
'tone',
'tons',
'too',
'took',
'tool',
'top',
'tops',
'tore',
'torn',
'toss',
'tour',
'tow',
'town',
'tows',
'toy',
'toys',
'trap',
'tray',
'tree',
'trek',
'trim',
'trig',
'trip',
'trod',
'trot',
'true',
'try',
'tty',
'ttys',
'tub',
'tube',
'tubs',
'tuck',
'tuft',
'tug',
'tugs',
'tune',
'turf',
'turn',
'twas',
'twig',
'twin',
'two',
'twos',
'type',
'ugh',
'ugly',
'undo',
'unit',
'unto',
'up',
'upon',
'ups',
'urge',
'urn',
'urns',
'us',
'use',
'used',
'user',
'uses',
'uucp',
'vale',
'van',
'vane',
'vans',
'vary',
'vase',
'vast',
'vat',
'vats',
'veal',
'veer',
'veil',
'vein',
'vend',
'vent',
'verb',
'very',
'vest',
'veto',
'vex',
'vi',
'via',
'vial',
'vice',
'vie',
'vied',
'vier',
'vies',
'view',
'vii',
'viii',
'vile',
'vine',
'vis',
'visa',
'vita',
'void',
'volt',
'vote',
'vow',
'vows',
'wade',
'waft',
'wag',
'wage',
'wags',
'wail',
'wait',
'wake',
'walk',
'wall',
'wan',
'wand',
'wane',
'want',
'war',
'ward',
'ware',
'warm',
'warn',
'warp',
'wars',
'wart',
'wary',
'was',
'wash',
'wasp',
'wave',
'wax',
'waxy',
'way',
'ways',
'we',
'weak',
'wean',
'wear',
'web',
'webs',
'wed',
'weds',
'wee',
'weed',
'week',
'weep',
'weld',
'well',
'went',
'wept',
'were',
'west',
'wet',
'wets',
'what',
'when',
'whew',
'whey',
'whim',
'whip',
'whit',
'whiz',
'who',
'whom',
'why',
'wick',
'wide',
'wife',
'wig',
'wigs',
'wild',
'wile',
'will',
'wilt',
'wily',
'win',
'wind',
'wine',
'wing',
'wink',
'wins',
'wipe',
'wire',
'wiry',
'wise',
'wish',
'wisp',
'wit',
'with',
'wits',
'woe',
'woke',
'wolf',
'womb',
'wont',
'woo',
'wood',
'woof',
'wool',
'woos',
'word',
'wore',
'work',
'worm',
'worn',
'wove',
'wrap',
'wren',
'writ',
'xi',
'xii',
'xiii',
'xiv',
'xix',
'xv',
'xvi',
'xvii',
'xx',
'yacc',
'yank',
'yard',
'yarn',
'yawn',
'yea',
'yeah',
'year',
'yeas',
'yell',
'yelp',
'yes',
'yet',
'yoke',
'yon',
'you',
'your',
'yuck',
'zap',
'zaps',
'zeal',
'zero',
'zest',
'zinc',
'zone',
'zoo',
'zoom',
'zoos'
           ]
  MALE_NAMES = %w(Jacob Michael Joshua Matthew Ethan Andrew Daniel William Joseph Christopher Anthony Ryan Nicholas 
    David Alexander Tyler James John Dylan Nathan Jonathan Brandon Samuel Christian Benjamin Zachary Logan Jose Noah 
    Justin Elijah Gabriel Caleb Kevin Austin Robert Thomas Connor Evan Aidan Jack Luke Jordan Angel Isaiah Isaac Jason 
    Jackson Hunter Cameron Gavin Mason Aaron Juan Kyle Charles Luis Adam Brian Aiden Eric Jayden Alex Bryan Sean Owen 
    Lucas Nathaniel Ian Jesus Carlos Adrian Diego Julian Cole Ashton Steven Jeremiah Timothy Chase Devin Seth Jaden Colin Cody Landon Carter Hayden Xavier Wyatt Dominic Richard Antonio Jesse Blake Sebastian Miguel Jake Alejandro Patrick)
  
  def random_male_name
    MALE_NAMES[rand(MALE_NAMES.size)]
  end
  
  FEMALE_NAMES = %w(Emily Emma Madison Olivia Hannah Abigail Isabella Ashley Samantha Elizabeth Alexis Sarah Grace 
    Alyssa Sophia Lauren Brianna Kayla Natalie Anna Jessica Taylor Chloe Hailey Ava Jasmine Sydney Victoria Ella Mia Morgan Julia Kaitlyn Rachel Katherine Megan Alexandra Jennifer Destiny Allison Savannah Haley Mackenzie Brooke Maria Nicole Makayla Trinity Kylie Kaylee Paige Lily Faith Zoe Stephanie Jenna Andrea Riley Katelyn Angelina Kimberly Madeline Mary Leah Lillian Michelle Amanda Sara Sofia Jordan Alexa Rebecca Gabrielle Caroline Vanessa Gabriella Avery Marissa Ariana Audrey Jada Autumn Evelyn Jocelyn Maya Arianna Isabel Amber Malanie Diana Danielle Siera Leslie Aaliyah Erin Amelia Molly Claire Bailey Melissa)
  
  def random_female_name
    FEMALE_NAMES[rand(FEMALE_NAMES.size)]
  end
  
  SURNAMES = %w(Smith Johnson Williams Jones Brown Davis Miller Wilson Moore Taylor Anderson Thomas Jackson White
    Harris Martin Thompson Garcia Martinez Robinson Clark Rodriguez Lewis Lee Walker Hall Allen Young Hernandez King 
    Wright Lopez Hill Scott Green Adams Baker Gonzalez Nelson Carter Mitchell Perez Roberts Turner Phillips Campbell 
    Parker Evans Edwards Collins Stewart Sanchez Morris Rogers Reed Cook Morgan Bell Murphy Bailey Rivera Cooper 
    Richardson Cox Howard Ward Torres Peterson Gray Ramirez James Watson Brooks Kelly Sanders Price Bennett Wood
    Barnes Ross Henderson Coleman Jenkins Perry Powell Long Patterson Hughes Flores Washington Butler Simmons Foster 
    Gonzales Bryant Alexander Russell Griffin Diaz Hayes Myers Ford Hamilton Graham Sullivan Wallace Woods Cole West 
    Jordan Owens Reynolds Fisher Ellis Harrison Gibson Mcdonald Cruz Marshall Ortiz Gomez Murray Freeman Wells Webb 
    Simpson Stevens Tucker Porter Hunter Hicks Crawford Henry Boyd Mason Morales Kennedy Warren Dixon Ramos Reyes 
    Burns Gordon Shaw Holmes Rice Robertson Hunt Black Daniels Palmer Mills Nichols Grant Knight Ferguson Rose Stone 
    Hawkins Dunn Perkins Hudson Spencer Gardner Stephens Payne Pierce Berry Matthews Arnold Wagner Willis Ray Watkins 
    Olson Carroll Duncan Snyder Hart Cunningham Bradley Lane Andrews Ruiz Harper Fox Riley Armstrong Carpenter Weaver 
    Greene Lawrence Elliott Chavez Sims Austin Peters Kelley Franklin Lawson Fields Gutierrez Ryan Schmidt Carr Vasquez
    Castillo Wheeler Chapman Oliver Montgomery Richards Williamson Johnston Banks Meyer Bishop Mccoy Howell Alvarez
    Morrison Hansen Fernandez Garza Harvey Little Burton Stanley Nguyen George Jacobs Reid Kim Fuller Lynch Dean
    Gilbert Garrett Romero Welch Larson Frazier Burke Hanson Day Mendoza Moreno Bowman Medina Fowler Brewer Hoffman
    Carlson Silva Pearson Holland Douglas Fleming Jensen Vargas Byrd Davidson Hopkins May Terry Herrera Wade
    Soto Walters Curtis Neal Caldwell Lowe Jennings Barnett Graves Jimenez Horton Shelton Barrett Obrien Castro
    Sutton Gregory Mckinney Lucas Miles Craig Rodriquez Chambers Holt Lambert Fletcher Watts Bates Hale
    Rhodes Pena Beck Newman Haynes Mcdaniel Mendez Bush Vaughn Parks Dawson Santiago Norris Hardy Love Steele
    Curry Powers Schultz Barker Guzman Page Munoz Ball Keller Chandler Weber Leonard Walsh Lyons Ramsey
    Wolfe Schneider Mullins Benson Sharp Bowen Daniel Barber Cummings Hines Baldwin Griffith Valdez Hubbard
    Salazar Reeves Warner Stevenson Burgess Santos Tate Cross Garner Mann Mack Moss Thornton Dennis Mcgee
    Farmer Delgado Aguilar Vega Glover Manning Cohen Harmon Rodgers Robbins Newton Todd Blair Higgins Ingram
    Reese Cannon Strickland Townsend Potter Goodwin Walton Rowe Hampton Ortega Patton Swanson Joseph Francis
    Goodman Maldonado Yates Becker Erickson Hodges Rios Conner Adkins Webster Norman Malone Hammond Flowers 
    Cobb Moody Quinn Blake Maxwell Pope Floyd Osborne Paul Mccarthy Guerrero Lindsey Estrada Sandoval
    Gibbs Tyler Gross Fitzgerald Stokes Doyle Sherman Saunders Wise Colon Gill Alvarado Greer Padilla
    Simon Waters Nunez Ballard Schwartz Mcbride Houston Christensen Klein Pratt Briggs Parsons Mclaughlin
    Zimmerman French Buchanan Moran Copeland Roy Pittman Brady Mccormick Holloway Brock Poole Frank Logan
    Owen Bass Marsh Drake Wong Jefferson Park Morton Abbott Sparks Patrick Norton Huff Clayton Massey
    Lloyd Figueroa Carson Bowers Roberson Barton Tran Lamb Harrington Casey Boone Cortez Clarke Mathis
    Singleton Wilkins Cain Bryan Underwood Hogan Mckenzie Collier Luna Phelps Mcguire Allison Bridges
    Wilkerson Nash Summers Atkins Wilcox Pitts Conley Marquez Burnett Richard Cochran Chase Davenport
    Hood Gates Clay Ayala Sawyer Roman Vazquez Dickerson Hodge Acosta Flynn Espinoza Nicholson Monroe
    Wolf Morrow Kirk Randall Anthony Whitaker Oconnor Skinner Ware Molina Kirby Huffman Bradford Charles
    Gilmore Dominguez Oneal Bruce Lang Combs Kramer Heath Hancock Gallagher Gaines Shaffer Short Wiggins
    Mathews Mcclain Fischer Wall Small Melton Hensley Bond Dyer Cameron Grimes Contreras Christian Wyatt
    Baxter Snow Mosley Shepherd Larsen Hoover Beasley Glenn Petersen Whitehead Meyers Keith Garrison Vincent
    Shields Horn Savage Olsen Schroeder Hartman Woodard Mueller Kemp Deleon Booth Patel Calhoun Wiley Eaton
    Cline Navarro Harrell Lester Humphrey Parrish Duran Hutchinson Hess Dorsey Bullock Robles Beard Dalton
    Avila Vance Rich Blackwell York Johns Blankenship Trevino Salinas Campos Pruitt Moses Callahan Golden
    Montoya Hardin Guerra Mcdowell Carey Stafford Gallegos Henson Wilkinson Booker Merritt Miranda Atkinson
    Orr Decker Hobbs Preston Tanner Knox Pacheco Stephenson Glass Rojas Serrano Marks Hickman English Sweeney
    Strong Prince Mcclure Conway Walter Roth Maynard Farrell Lowery Hurst Nixon Weiss Trujillo Ellison Sloan
    Juarez Winters Mclean Randolph Leon Boyer Villarreal Mccall Gentry Carrillo Kent Ayers Lara Shannon Sexton
    Pace Hull Leblanc Browning Velasquez Leach Chang House Sellers Herring Noble Foley Bartlett Mercado Landry
    Durham Walls Barr Mckee Bauer Rivers Everett Bradshaw Pugh Velez Rush Estes Dodson Morse Sheppard Weeks
    Camacho Bean Barron Livingston Middleton Spears Branch Blevins Chen Kerr Mcconnell Hatfield Harding 
    Ashley Solis Herman Frost Giles Blackburn William Pennington Woodward Finley Mcintosh Koch Best Solomon
    Mccullough Dudley Nolan Blanchard Rivas Brennan Mejia Kane Benton Joyce Buckley Haley Valentine Maddox
    Russo Mcknight Buck Moon Mcmillan Crosby Berg Dotson Mays Roach Church Chan Richmond Meadows Faulkner 
    Oneill Knapp Kline Barry Ochoa Jacobson Gay Avery Hendricks Horne Shepard Hebert Cherry Cardenas Mcintyre
    Whitney Waller Holman Donaldson Cantu Terrell Morin Gillespie Fuentes Tillman Sanford Bentley Peck Key Salas
    Rollins Gamble Dickson Battle Santana Cabrera Cervantes Howe Hinton Hurley Spence Zamora Yang Mcneil Suarez
    Case Petty Gould Mcfarland Sampson Carver Bray Rosario Macdonald Stout Hester Melendez Dillon Farley Hopper
    Galloway Potts Bernard Joyner Stein Aguirre Osborn Mercer Bender Franco Rowland Sykes Benjamin Travis Pickett
    Crane Sears Mayo Dunlap Hayden Wilder Mckay Coffey Mccarty Ewing Cooley Vaughan Bonner Cotton Holder Stark
    Ferrell Cantrell Fulton Lynn Lott Calderon Rosa Pollard Hooper Burch Mullen Fry Riddle Levy David Duke Odonnell
    Guy Michael Britt Frederick Daugherty Berger Dillard Alston Jarvis Frye Riggs Chaney Odom Duffy Fitzpatrick
    Valenzuela Merrill Mayer Alford Mcpherson Acevedo Donovan Barrera Albert Cote Reilly Compton Raymond Mooney 
    Mcgowan Craft Cleveland Clemons Wynn Nielsen Baird Stanton Snider Rosales Bright Witt Stuart Hays Holden 
    Rutledge Kinney Clements Castaneda Slater Hahn Emerson Conrad Burks Delaney Pate Lancaster Sweet Justice
    Tyson Sharpe Whitfield Talley Macias Irwin Burris Ratliff Mccray Madden Kaufman Beach Goff Cash Bolton 
    Mcfadden Levine Good Byers Kirkland Kidd Workman Carney Dale Mcleod Holcomb England Finch Head Burt Hendrix 
    Sosa Haney Franks Sargent Nieves Downs Rasmussen Bird Hewitt Lindsay Foreman Valencia Oneil Delacruz)

  def random_surname
    SURNAMES[rand(SURNAMES.size)]
  end
   
  USERNAMES = %w(78450774534boysahah 11640 16913 21300 22cutepuppies 2cute2beU 2tall 35224zixzox 35266 
  3hugz2heartz1love 50cent 5pennies 6666666666 666grayfox666 abagail abhinav abiagil aboutalover 
  AdollAbill AFASDFDFDFSDF afoolishfool Afra7Suli4everLove AHNAH aimee alannag alannah AlexisBraziel ALEXUS 
  alicat Alicia AllieKiernan AmAnDarulestheschool ameersaad amyrogers anaconda anditshurds andrei andres
  andrewnikedunk angelfire Anilisthebes ANIMAL ANIMALWHATDOESITMEAN anisha AnkurXxXx annihillator anson Anthony
  AnticrisT appleorange armaro armerstarkers arranmasterman arthur asdfghjkl Ashleifg ashley attackofthebignose
  aurelie ayman babbygurl BabeJ babiley babypink BabyBoo Babybuby babygigglez babyllama babyphat BabyPhat
  BadDog1423 BadMan baker bamnigga BamSuckaFish BARBIEGIRL barny baSsicInstinct01 bathroom batteredsausage 
  bbchic Beaner beatriz beccaishott beckstar Beckstar BeHappy BELAJOSANAC Bells BenCheong BENJO benniefat benny 
  benz0r benzin4me betsy betul bewarebitchahed BibleBanger bigdumbbitch biglooka Bigslim bigworm billabong 
  BillieDynamite bingo binky biotch bitches bitchisabadthing BiZzKiT bizznotch BJBarry blablaidntno BlackFox 
  Blackiechan BlackMaGic BlairAlston blairisalegend BLAKEIZAHAMBOY Blingj Blink blinkflikhotmailcom blodboy 
  Blondeheart Blondie BloodCountess BloodyTears bluefoxhawk1 bluey bolammers bogart boobyhead boog booga Booger 
  Boogs boohilary bored boswerth botheredbiatchesxx boyfriend boyzcomeandgo BRANDO BRAWLA Brenda BrionyLeaWills 
  Brizddaclown brosoverhos Brownie BrownieBoy bubblebuddy BubbleToes buburuzatm bugle bulletra burnthebearinhell
  BuTtOns bytchaR bzyne cahonies CAhViLLe CahViLLeBaLLa callofduty calum camila candybaby canks Cansy CARITA 
  carlosbeaner carnivore carressa carrisma94hotmailcom carso cassie9690501 Cbury CEAPACALITA chales chaman 
  chandelier Chandler changfizzle changfu chapstick charchar cHarlie Charlie CHARLOTTE charnuts CHARONTIRRORISTE
  chasingpapi chave chealse Chedda cheesecake chiara chicana chickenshizzle Chickmagnet Chickster chimchim chloe
  chrisco Chrisi chrispbacon christeen ChRiStIaNGuRl ChristieHer CHUBAKA chunkymonkey chzelle classymashyjessie
  Clavius clayton clemens climaximum cocksmacker cokesucks CoLdStOrM CompUTaWiz ComUTaWIZ connorpaterson conteh
  coolcool coolj Cootsie cordelia cornerworker couNti CountryGal17 CrACkinNdAHoOd craftlady Crayzlove Crazybabe
  crazybrat crazychick cripsalot crusher crusty Csaba CstrikeN003 cuddlycassie cumlover cutesie CutiePie Cyrus
  D3pthCh4rg3 d3s2ny0 D4rkTears DADDYDOLLS damselinthisdress dang Danielslover Danya DARKSIDE darla Darnell darnella
  DeadlyWhispers DeadMan deciving DeeDeeSlim Deidre denicia denise Derrik Destiny devin Devious diablodork Diegox
  Dilson dingswhenready dipset4lyfegangsta DirtySanchez dizzie donnell dontmarryforeiners doodlebug dooey douliveinBDA
  doyouhavepussylickit drastick drdriedal DrEaMeR drewsmillie duditz dustinandrew Dylan ebone Eased ebubekir
  echthe edgartorres efkalesnami efren eilidh elescribe elgallo elias ElleorDelli elmar ElwoodFunlump Elyse Eminems
  emmaisalesbo Emmaturnerplaysguys emmie EmOKid emokid336 emoney Ericka ericpalma eristsogtzuiopü ERTERT 
  esraaisthesexiest EVINKESKIN ewald EXFRENDJESSEY faaris Fabio fares fartface farukgokcen fasthands FatCatBob
  fatfunfoot fatfunfoot fatpigbut FatturkieFurkie female Ferious finyekeh final Fishstick Fizziwig floppy flowrr
  Foofi foolish forgetthename fORMATER FoshEEdo freakshow frenchy Fresh frost FryKid frzburn funay furby Futor
  gabboo GaNgStAlOzZy Gangster gansgta4lyfe garbear Gardos Garebear gareth garew gaylife gaylordfakker Geforce
  GeMMa GeorgeSmith ghettoguyanese giantpenis ginge GISMO gmoney GodsPricelessTeaCuo golob goothy Gorman grappig
  grilledchicken Grod3n Guera guppy HaCKeR hahaa hahah HajerBest HajerRATELILUVEU HAJERUBROKEMYHEART hangwithwang
  haramzada HardcoreBiker Haresh HARPEERKFKGJKG Harry harryballs hayrettin hazel heartlessarchangel HeartlessArchangel
  heatbag hecallsmeBabe HEEEEEEBLAAAAAA hellokitty hellsangle HEMANAGAMANCHA HEPZILLA heythisisaname hfgbhydythngn
  Hiimsototallygaygay Hilde hitman HLBG hobojoe HonaHonaBord Honeylove horseynicknames HotRod hotsauce
  houstonmcdaniel humor hushpuppy huuchimama HzelEyez Iceman ICEMAN Iheartjess IINSOMNIA ilikemen iliketoshaggmonkeys
  ilikeyouyouaregood ILLUMINATI ilovealexis ilovebrielle ilovedylanandkira ilovemanu iloveyouu imagayboy
  Imgoingtokillyou iMnOtShY innergiant innocentdevil IntelInside ironhands ironmike IvanaTinkle iverson ivvet
  Izzy7777777 IzzyMiiNizzy Jbug JACKOISDEAD janette jasonia JayBird jaydee jbeezy jeffsy jenniehill Jenny
  jenster Jenzz jessicasolomakha jessie jessika jewers JH4eva jhandubalm jimmy Jimsaloverboy JingJing Jiordano
  joejoe joemamasan joesmells johnmack johnnybigbollox jojojimbob jolenebuckedtilly jolenelvstilly jolit Jordi
  Jordy jorian jquan JuDgMeNT JUICY JuliaDorey julius Justin JUSTINSKYWALKER kabe kafasi kaidi Kaiser Kaitlin 
  kalle kanie Karan Karlee Karleesashitface kasey kasey katy Kaylean kaylene kdkdkdkdkdkdkdkd keke kel02
  kennykencola kenzie kevinohare KEVLORD kfizzleandjwizzle khjkljuhkljn kidwonder kieron Kiersten KILLA4LIFE 
  KillaJokes KILLER Kimber Kinsall kirababy KirstylovesJamie kizno kizzix Klapon klBabykl klipzdude kngpn 
  knockoutkid knowles kodered KoKet kommanda krackalacka Kristan krukut KUSHJARRUSHJA lacrazygirl LacrazyGirlAKAkarina
  ladylovlybird LaFlaka lakey laksjdfietnt lara LAURANCY laurel LAUREN laydeefloss lazysexydester LCLuckyCharms
  Lelainia lemonloom leodavester Leona leonel letisopi libby lightbilb lighteninggal LilBabyGansta lilbabygirl
  LilLybrook lilmisssmitty lilrider lilshorti lilsmokie lilspooky lilyiz limitz linden lippleas Lippwizz
  lishiybertischyert litleb littlemissy littlebabyprincess lizzle lolipop lollipoops looly LoopyLou Lordarcher
  lorene LorenesucksDick lorlay Lotte loverface Luanne Lucilla ludachic Lufthansa lugsie LuVaBlEBaBy luvbug
  LuVyahunxxx m0rdi Maddox maggit Mahad mahta maiyoya makkan malinmaria mamallama Manitu marcoalexgayylovers
  Maria marmar masood Matt mattches matthewlewis maurice MaXii MaxLiedtkaisGod Meecho MEHMETCAN MelatoninRonin
  memosh menafaresfunny menameCHAINZCOOLRITE MetalHead miauk Michaeldoyle mikeymike mikhail mikol minty Mitisha
  mmmmmmmmmmmhmmmmmmm mmmmmmmmmmmm mmurhudufsormok Mofomotha momnurse mongi monstergirl moozenindahouse
  morbidprincess mosny mOuseGirL mrfunktastic MrFrazzle mrhankey mrhockey MrIndependent MrKinsall mrlove MrMoop
  mrpond Mrspop MrStayPuft MrVonTinkleschmidt msnewbooty muchkin muffinhead munchbunch munchinmonster murali
  mushi MUSHYPEASMUSHMUSH mustang muzza myscreenname4aol n0bed N1NJ4 Nabisco NaDeEn nameless23 nampumpsdaliah
  nasjian nasty NATHANANDJORDAN nathanwalker NAYLTONOLIVEIRA negro NeKaBoO nerfist netfali5hotmailcom newkid
  nichola nicknamesstink nicknongo nickygirl nicolle NiggaLips NIKEL nikki nitulina noaim nobby noblet noctoriousfart
  Nofearnameishere nojansmommasofat nomadnocry Norge Norman NOTHIN notquiteanangel NUMBA1 numbnuts nunuubarfboy
  nytuyuuiyu oakley OGGANGSTACRIP oidocuzimahotgirl OKTHEN oLIVIA OMGYALLSUCK oopsididitagain ooSUCKMYNIPPLEZ
  orangeapple orgen OrlandoKendricks Oscargutierrz otaku paddystar pamplemousse pamplemousse panchito parapia
  Pascal pattywatty pauldeliso PAWA PCHUNKY pdeezy Peachbear peefi pelin pencildicks PGpicklegirl phantasystar
  phantasystayr phillip PHOISY Phrysphere pickleberry Pimpcess7 pinkoanther pinkpanther pinkie pinsel PixieCorpse
  playagirl playboychic PlAyGiRl4LiFe playmaker pollabears pondaldinho pondy poobar poobear poodachandi Poodie
  poohead pookiewoookiepoopoo poonut POOPDACE porfiacto POWERCENTERamdDuron princyppiiisa Priscilla ProPuke
  prostitu PsychoCandy PsycHoPaT3 pudding puppyluv pussyandfries Qbanitoo QUIANACOOPER Quinisgay Quinn Quish qwerty
  rachy ramjam rammstein randy rarahoops rasheve rashy rebal RebalBabe rebekahghosh REDDAC RedSHOT Reese REESE
  remopotore renagade respina ricecrispyboy Rihann ripley Robbi robit rodney rosey rosie rossums RudeBoy2Hot2Handle
  rugay rumardi RUPERT rusto Ryaen Ryane rypie saamit sadename sadenicknames sagar Saggynanny Sajar salma samet
  Sandra Sandroff SantaClaus scabs scarletjoehansing schmoodle scruffy sdgdf seannah sechin senozlu SEXMASTER
  sexuufemaledog SEXYANGELBloNde Shabdu ShaggyButt shagsta ShaunMcfadyen shawnjohnson shazzy SheDevil sheash sherk
  Shibby Shivvers shizza shizzy Shmoph Shock shortbus shortstuff showstopper shrew shrimp Shrimpie Shrimpy shygurl
  SiamZamir sidewinder silliedillie skidds skwee SkyWalker slappie slothy smakthtbottm smiler SmokingDro24 smuge
  SnickleFritz snipa snookles snoopdizzle SnowBunny snugglebug soark soccerchick social sockmonkey softfuzzyyballls
  sohair Sojerfoos SoLiDbReaKeR soooscrewhim Sophia sophieluvinconnor southernboyswow spaRx Spazzy spencer squeaky
  SQUIDY squishych33ks srhissexy staysick911StudMuffin stupidboysnicks Sugarbaby SugarLoaf Suite sukkeltje sumgrills
  SuperioR SURRULES suspect susspekt swadie sweatness Sweetie switchblade Tales TallinHeels Taria tbone
  Teenieboppertravels teezykibeera thachronic thebestman theblackrooster thedarkmissis theflame thehitman thelud
  TheMailMan TheMItchmyster theonlyrafan thepond ThePringle thereason TheSchitt TheSolution TheStuff TheYouKnowWho
  thief thinair ThomasisaStudMuffin thomson tiearrah tinkrbell Titch titster titushka tomatoface tootall topbloke
  Torque torri Torvill ToyToy tradere travypoo Trebla Tupitufito turnergirl Turtle tuster TwinkleToes TWINKLETOOES
  umamafattie unanut Undragon upnatem upsidedown uradreamcometrue urbigsexymama urmasterpiece USUCK
  utjwariorschaoscrew vaigra Vapour velox VenezolanaRebelde viagraman vidal Viktoria vitale VITIGOGNITTI
  VivaAndromeda vjosa VoodooPrudence Vortex vrienzy vVoVv warpen Warsame wateva websta wednesday weejimmy weird
  weirdo wenisa WeSTSiDeCRiP whatisyouraddy whatsupwithunurqus Whipstank whiters wholovesyababy whowantsmycock
  wilden Willtynda winky winnielovesyou wivstar Wonton wordsandgames wotisuraddy wotsuraddyLOL wower X4rt3c
  xAbs0lut3x Xaracuz XiteZite xxbabyfacexx yasmine Yoguyzngalz yojay16 yourmomgoestocollege Yowotsuraddy YoYoHanZi
  yuliansilly zambo ZebraLuvurIzzy zenaida Zeratool zerocool Ziggy zigzag zipzap zixzox Zonster Zoopy zorbeyyy58)

  def random_username
    USERNAMES[rand(USERNAMES.size)]
  end
    
LONG_TEXT_1 = ["To whom it may concern,",
            "Hiya!",
            "I wrote to you some time ago, but as yet I have heard nothing from you. I'm not quite sure what to make of this fact, so I decided to write to you again. As you can see from the subject line of this message, the matter is very urgent.",
            "How are you?",
            "I just thought I'd drop you a line to see how you are.",
            "Don't you agree that there is nothing more important than this right now?",
            "Dear Sir",
            "I am writing to you because I am the representative of the Vatican in this country.",
            "Peace, man,",
            "Hi!",
            "Hello...",
            "What the...???"
            ]
            
  LONG_TEXT_2 = ["Bla bla bla bla bla bla bla bla bla bla bla?",
            "Okka okka okka okka okka okka okka okka okka okka okka okka. Uk uk.",
            "Nessun dorma. Fis ofisasd foi pdsofig oasindd iosdufhjg oiasd oisjd foijsdfsdf sklduifhj sodjf osid fosd ofsldmf sdfsdf, oisdjf osidm foams dad,iopu sodifjsdf. IGOLOLOLO siodfsdf sdfs!!! Ijsd fij FGiojuw pojkwf okokokokokokokok asdifjs dfsf -- nsdifix NIXDORF isjd fiouh qwdoij sdflknsdf....   Foa GOOA CI sdifjsdjf isf iiiiik iiik...!",
            "O Fortuna, velut Luna statu variabilis, semper crescis aut decrescis; vita detestabilis nunc obdurat et tunc curat ludo mentis aciem; egestatem, potestatem, dissolvit ut glaciem.",
            "Sors immanis et inanis, rota tu volubilis, status malus, vana salus semper dissolubilis; obumbrata et velata mihi quoque niteris; nunc per ludum dorsum nudum fero tui sceleris.", 
            "Sors salutis et virtutis mihi nunc contraria; est affectus et defectus semper in angaria. Hac in hora sine mora cordae pulsum tangite! quod per sortem sternit fortem, mecum omnes plangite!",
            "Ego sum abbas Cucaniensis et consilium meum est cum bibulis, et in secta Decii voluntas mea est, et qui mane me quaesierit in taberna post vesperam nudus egredietur, et sic denudatus veste clamabit: Wafna, wafna! quid fecisti, Sors turpissima? nostrae vitae gaudia abstulisti omnia!",
            "Milli Vanilli - the best band EVER!",
            "Nobody knows the trouble I've seen. Nobody knows but George Bush.",
            "Sebastian Arce and Mariana Montes are outstanding teachers of the very highest level: clear, concise, humorous and always to the point, coupled with a thorough understanding of the students' needs. Their style of dancing and teaching encompasses all styles, being rooted in a solid classical technique but taking in all new techniques and approaches to teaching. Sebastian came to tango at the tender age of 8 and as a teenager already had performed in practically all tango shows in Buenos Aires and internationally. Mariana began her career as a folklore dancer and was part of the Salta Ballet. They have also appeared in the films Evita (starring Madonna), in Carlos Saura's Tango, and in Happy Together. Sebastian and Mariana are in high demand worldwide: they are simply among the very best, on stage and as teachers.",
            "You need to know the following: the history of the building begins in 1878 when the Great Hall of the Royal Musical Academy of Sweden was inaugurated by King Oscar II. It rapidly became the centre of the musical life of Sweden.",
            "It's LE PRIÈURÉ DE SION, I tell you! And they're after us!",
            "The Ensemble has collaborated with various bandoneonists as Daniel Binelli, Luis Stazo, Hector Raul \"Tito\" Cartechini, Peter Reil, Josè Luis Betancor, Marisa Mercadè, Massimiliano Pitocco, Gilberto Pereyra, Veronique Rioux, and others. These fruitful collaborations has added a deeper dimension to the Hyperion Ensemble's already intense, artistic character.",
            "Mario Orlando is undoubtedly the most famous tango DJ in the world. He plays regularly in all the most prestigious and well-known milongas, but he also appears in a number of underground and alternative places. We are extremely proud to present — for the first time ever outside of Argentina — Mario Orlando to the Tango 59° audience. This is a unique opportunity to meet and dance to the music of a true DJ legend, one who defines the art of tango DJ:ing.",
            "Once upon a midnight dreary, while I pondered, weak and weary, Over many a quaint and curious volume of forgotten lore, While I nodded, nearly napping, suddenly there came a tapping, As of someone gently rapping, rapping at my chamber door. \" 'Tis some visitor,\" I muttered, \"tapping at my chamber door; Only this, and nothing more.\"",
            "The tomb of the old Hyde family held a fatal attraction for Jervas Dudley until he communed with the dead and learned their secrets.",
            "I'm dreaming of a dead city Where Deep Ones swim in depths of night Where Cthulhu's sleeping And stars go creeping Until the time when they are right",
            "Wendigoes Wendigoes - walking in the waste They will soon be whooshing by to find out how you taste - oh! Wendigoes Wendigoes hear the North Wind moan Quicker than the frost will melt they'll strip you to the bone",
            "Remember, remember the fifth of November, the Gunpowder Treason and Plot. I see no reason why Gunpowder Treason should ever be forgot.",
            "Guy Fawkes, Guy Fawkes, 'twas his intent, to blow up the King and the Parliament. Three score barrels of powder below, Poor old England to overthrow: By God's providence he was catch'd With a dark lantern and burning match. Holloa boys, holloa boys, make the bells ring. Holloa boys, holloa boys, God save the King! Hip hip hoorah!",
            "A penny loaf to feed the Pope, A farthing o' cheese to choke him. A pint of beer to rinse it down, A faggot of sticks to burn him. Burn him in a tub of tar, Burn him like a blazing star. Burn his body from his head, Then we'll say ol' Pope is dead. Hip hip hoorah! Hip hip hoorah!",
            "How do you do, I see you've met my faithful handyman. He's just a little brought down, because when you knocked, he thought you were the candyman."
            ]    
  
  LONG_TEXT_3 = ["Take care.",
            "See you around!",
            "I'll give you a ring later tonight.",
            "Bye.",
            "For the sake of the widow's son.",
            "May the Force be with you.",
            "Farewell.",
            "In LVX",
            "Live long and prosper!",
            "Yours truly.",
            "Ciao.",
            "So there.",
            "I remain for ever your loyal servant.",
            "You will *never* get away with this, I tell you.",
            "Aight.",
            "Do What Thou Wilt Shall Be The Whole Of The Law."
            ]
	
	def random_long
    result = LONG_TEXT_1[rand(LONG_TEXT_1.size)] + "\n\n"  
    for i in 1..(rand(5)+1)
      result.concat(LONG_TEXT_2[rand(LONG_TEXT_2.size)] + "\n\n")
    end 
    result.concat(LONG_TEXT_3[rand(LONG_TEXT_3.size)])  
    
    result.squeeze(' ')
  end

  TEXT_1 = ['I','You','We','They','The CIA',"My solicitors",'The police','I just','Hey! I', 'They said you', 'Someone said you',
              'Howdy! I','What? I', 'I said I', 'MI5', 'Stop! You said you', 'You said I', 'I was told you', 'All rock bands', 
              'Many punk bands', 'Goths', 'Metal fans', 'Cock rockers', 'Latin music lovers','The FBI','Trekkies', 'Wetbadgers',
              'Fashion victims', 'We think you', 'Somebody mentioned that you', 'We have proof that you', "Don't deny that you",
              'Queer theoreticians', 'Modern people', 'The young', 'Jetsetters', 'Drug users', 'Sex addicts', 'AA members',
              'Nerdy gynaecologists', 'Your parents', 'All church-goers', 'The conservative party', 'You', 'We', 'They',
              'Someone said that you', 'We think you', 'We know that you', 'A friend assured me that you', 'Nobody likes that you',
              'It is unacceptable that you', 'Pop stars', 'Jetsetters', 'Thin people', 'Fat people', 'Happy people', 'Sad people',
              'Famous film stars', 'Celebrities', 'Our best friends', 'Mensa members', 'Game show hosts', 'Newscasters',
              'Psychopaths', 'Kabbalists', 'Only psychos', 'You', 'You', 'You', 'You and I', 'TV evangelists', 'Blizzard',
              'Trig members', 'Adocca staff', 'People in Surrey', 'Felix readers', 'Most people', 'All average Joes', 'Porn stars',
              'Royalty', 'Fat people', 'Thin people', 'Robots']

  TEXT_2 = ['really','so','often','must','should','sometimes','hardly','always','never','secretly','openly','barely',
              '','','','','','','','','','','','']
  TEXT_3 = ['love', "don't love",'hate','like','adore','want to kill','need','loathe','try to look like','bonk',
              'need to contact','walk with','have had','have fun with','crave','play with','accost','are into','are totally into',
              'snog with','phone','sneeze on','spy on','look at','are interested in','dig','eviscerate','often impersonate',
              'promote','trade places with','think I am','fornicate with','go berserk over','get excited over',
              'look like','smell like','eat like','dress like','marry','expose yourself to','stalk','follow the example of',
              'trig on','stalk','want sexy pics of','never find','are clueless about','phone','mess with',
              'diss','underestimate','blackmail','want to forget about','would die for','badly need','love everybody except',
              'eat', 'will eat', 'will own', 'totally own', 'manhandle', 'innervate', 'want to be like', 'want to sleep with',
              'fondle','mystify','shock','murder','kidnap','examine','are fascinated by','are a bit like','taste like','burn like',
              'are buried like','doubt the existence of','doubt the veracity of','are inspired by','are put off by',
              'crave','wonder about','clean up after']
  TEXT_4 = ['you','myself','a dog','a cat','a small furry animal','the underage','someone','the IRS','Hitler', 'Madonna',
              'a hamburger','more food','a lasagna','God','Satan','Elton John','everybody','the elderly','the poor',
              'Brad Pitt','Angelina Jolie','Demis Roussos','Liberace','the YMCA','Beatrix Potter','my budgie','a wreck',
              'Göran Persson','the FBI','Mustafa Çan','a mortician','Siegfried & Roy','Oprah','a wino','J-Lo','Toby','50c',
              'the Mormon Tabernacle Choir','the hired help','a neural network','Gandhi','Deepak Chopra','the real thing',
              'an illusion','the mentally handicapped','the Japanese','anyone','gay people', 'all disco dancers', 
              'gospel music fans', 'grunge nostalgics', 'Elvis', 'Elvis Costello', 'Maria Carey', 'Gary Glitter',
              'KC & the Sunshine band', 'New York gallery owners', 'the rich', 'anybody', 'MC Hammer', 'Eminem', 
              'a republican', 'the straight', 'a democrat', 'the FBI', 'The Mysterons', 'fashion victims', 
              'Californian airheads', 'the Hollywood Kabbala crowd', 'Penn & Teller', 'geeks', 'suckers', 'imperialist fascist pigs',
              'the Pro Life movement', 'the middle classes', 'the Scottish', 'Geordies', 'Micks', 'Australians',
              'Trig members', 'Adocca staff', 'World of Warcraft players', 'your guildies', 'the guildless', 'your mama',
              'other people','Kate Moss','Isabella Rossellini','your nightmares','your mental state','your friends',
              'your enemies','your body','my body','my life','Versace','Hugo Boss','Vogue','Karl Lagerfelt','Chanel',
              'cock rockers', 'royalty', 'teenagers', 'adolescents', 'adults', 'the overweight', 'the thin and gorgeous',
              'robots', 'androids']
              
	def random_short(length = 70)
    (TEXT_1[rand(TEXT_1.size)] + ' ' + TEXT_2[rand(TEXT_2.size)] + ' ' + 
     TEXT_3[rand(TEXT_3.size)] + ' ' + TEXT_4[rand(TEXT_4.size)]).squeeze(' ')[0...length]
  end

  SINGLE_PARTS = ['you','myself','a dog','a cat','a small furry animal','the underage','someone','the IRS','Hitler', 'Madonna',
              'a hamburger','more food','a lasagna','God','Satan','Elton John','everybody','the elderly','the poor',
              'Brad Pitt','Angelina Jolie','Demis Roussos','Liberace','the YMCA','Beatrix Potter','my budgie','a wreck',
              'Göran Persson','the FBI','Mustafa Çan','a mortician','Siegfried & Roy','Oprah','a wino','J-Lo','Toby','50c',
              'the Mormon Tabernacle Choir','the hired help','a neural network','Gandhi','Deepak Chopra','the real thing',
              'an illusion','the mentally handicapped','the Japanese','anyone','gay people', 'all disco dancers', 
              'gospel music fans', 'grunge nostalgics', 'Elvis', 'Elvis Costello', 'Maria Carey', 'Gary Glitter',
              'KC & the Sunshine band', 'New York gallery owners', 'the rich', 'anybody', 'MC Hammer', 'Eminem', 
              'a republican', 'the straight', 'a democrat', 'the FBI', 'The Mysterons', 'fashion victims', 
              'Californian airheads', 'the Hollywood Kabbala crowd', 'Penn & Teller', 'geeks', 'suckers', 'imperialist fascist pigs',
              'the Pro Life movement', 'the middle classes', 'the Scottish', 'Geordies', 'Micks', 'Australians',
              'Trig members', 'Adocca staff', 'World of Warcraft players', 'your guildies', 'the guildless', 'your mama',
              'other people','Kate Moss','Isabella Rossellini','your nightmares','your mental state','your friends',
              'your enemies','your body','my body','my life','Versace','Hugo Boss','Vogue','Karl Lagerfelt','Chanel',
              'cock rockers', 'royalty', 'teenagers', 'adolescents', 'adults', 'the overweight', 'the thin and gorgeous',
              'robots', 'androids']
  
  def random_single
    SINGLE_PARTS[rand(SINGLE_PARTS.size)].capitalize
  end

  def produce(n)
    Array.new(n).collect do |e|
      CHUNKS[rand(CHUNKS.size)]
    end.join(".").downcase
  end

  def morph_login(login)
    login = login.downcase.gsub(/\s/, "")
    morphs = [:inator, :ored, :ed, :own, :age, :xor, :ck, :er, :leetz, :leetw2, :leetx, :leetw, :leets4, :leeto2, :leetg, :leetf2, :leetb, :leets3, :leets2, :leets, :leetf, :leetc, :rovar, :leeta, :leete, :leetl, :leett, :leeto, :zor, :ster, :lor, :prependnr1, :first, :iam, :thereal, :appendnr1, :forreal, :prependn, :appendn]
    morph = morphs[rand(morphs.size)]
    stripped = login.gsub(/[aoueiy]*$/, "")
    case morph
    when :inator
      "#{stripped.gsub(/i?n?a?$/, "")}inator"
    when :ed
      login.gsub(/ed$/, "t")
    when :ored
      login.gsub(/or$/, "ored")
    when :own
      login.gsub(/own/, "pwn")
    when :age
      "#{login}age"
    when :ck
      login.gsub(/ck/, "x")
    when :er
      login.gsub(/er$/, "or")
    when :leetz
      login.gsub(/z/, "s")
    when :leetw2
      login.gsub(/w/, "dubya")
    when :leetb
      login.gsub(/b/, "8")
    when :leetx
      login.gsub(/x/, "ecks")
    when :leetw
      login.gsub(/w/, "vv")
    when :leets4
      login.gsub(/s/, "ehs")
    when :leeto2
      login.gsub(/o/, "oh")
    when :leetg
      login.gsub(/g/, "6")
    when :leetf2
      login.gsub(/f/, "v")
    when :leeta
      login.gsub(/a/, "4")
    when :leets3
      login.gsub(/s/, "5")
    when :leete
      login.gsub(/e/, "3")
    when :leetl
      login.gsub(/l/, "1")
    when :leett
      login.gsub(/t/, "7")
    when :leeto
      login.gsub(/o/, "0")
    when :leets
      login.gsub(/s/, "z")
    when :leets2
      login.gsub(/s/, "c")
    when :leetf
      login.gsub(/f/, "ph")
    when :leetc
      login.gsub(/c/, "k")
    when :rovar
      login.gsub(/([cdfghklmnpqrstvwxz])/, "\\1o\\1")
    when :zor
      "#{stripped.gsub(/[szx]+/, "")}zor"
    when :xor
      "#{stripped.gsub(/x$/, "")}xor"
    when :ster
      "#{stripped.gsub(/s$/, "")}ster"
    when :lor
      "#{stripped.gsub(/l$/, "")}lor"
    when :iam
      "iam#{login}"
    when :thereal
      "thereal#{login}"
    when :appendnr1
      "#{login}nr1"
    when :forreal
      "#{login}forreal"
    when :prependnr1
      "nr1#{login}"
    when :first
      "thefirst#{login}"
    when :prependn
      "#{rand(100)}#{login}"
    when :appendn
      "#{login}#{rand(100)}"
    else
      raise "unknown morph #{morph}"
    end
  end
  
  module_function :produce, :random_single, :random_short, :random_long, :morph_login, :random_male_name, :random_female_name, :random_surname, :random_username

end
